apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: default
spec:
  type: state.postgresql
  version: v1
  metadata:
    - name: connectionString
      value: "host=neon.db user=neondb_owner password=YOUR_PASSWORD dbname=neondb sslmode=require"  # Update with your Neon DB connection string
    - name: maxIdleConns
      value: "10"
    - name: maxOpenConns
      value: "10"

